### ISSUE TITLE
spectatortheaterコマンドを初期状態で全プレイヤーが使えるのは普通にまずそう

### ISSUE THREAD

**Issue by Lucky3028** [SigureRuri/SpectatorTheater#1]
https://github.com/SigureRuri/SpectatorTheater/blob/0d6d8c5a5a8139b4429873ce23216c82a32a22a8/src/main/resources/plugin.yml#L11-L13

**Comment by Lucky3028** [comment]
`false`または`op`が適切だと思われる

**Comment by SigureRuri** [comment]
確かにそうですね、`op`に変更します。
