### ISSUE TITLE
feature: 現在本プラグインでスペクテイターになっているプレイヤーの一覧表示機能

### ISSUE THREAD

**Issue by Lucky3028** [SigureRuri/SpectatorTheater#2]

**Comment by SigureRuri** [comment]
現状のspectatortheaterコマンドと権限を分けたほうが良いですか？
@Lucky3028

**Comment by SigureRuri** [comment]
明日から私事で忙しくなるので今日のうちに 38a73ded25f1b2cc155e2c31840aaea9beb9112c でそれぞれ権限を変える方向で実装してしまいました。
詳しくはREADMEに書きましたがこれに合わせていままでとコマンド実行に必要な権限が少し変わっています。
確認が取れないままで申し訳ないです(もしかして通知届いてないですかね？)
