### ISSUE TITLE
パーミッション名が不必要に長い

### ISSUE THREAD

**Issue by Lucky3028** [SigureRuri/SpectatorTheater#4]
プラグイン名がかぶることは早々ないので、`spectatortheater.start`のようで十分だと思われます

**Comment by SigureRuri** [comment]
`[plugin name].command.[command name]`の形はbukkitで実装されているコマンドのパーミッションの命名(例:`bukkit.command.reload`)と合わせていたのですが、そちらのほうが都合が良いのであれば変更しておきますね。
